name: Generate Pacman Graph

on:
  # Otomatis berjalan setiap hari jam 12 malam
  schedule:
    - cron: "0 0 * * *"
  # Memungkinkan Anda menjalankan manual kapan saja
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Menggunakan Action resmi Pacman Graph
      - uses: abozanona/pacman-contribution-graph@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
