name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Memaksa checkout menggunakan token Anda, bukan token bawaan robot
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: falaizadev
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Melakukan push menggunakan otentikasi token rahasia Anda
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pacman.svg
          git commit -m "Update Pacman Contribution Graph" || exit 0
          git push
